#!/usr/bin/env bash
# Detect v2rayN / Xray (or similar) listen ports on the host and write
# docker-compose.override.yml so the bot container can reach them.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="$ROOT/docker-compose.override.yml"

port_open() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -lnt 2>/dev/null | grep -qE ":${port}([^0-9]|$)"
    return $?
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  timeout 1 bash -c "echo >/dev/tcp/127.0.0.1/${port}" 2>/dev/null
}

first_open() {
  local port
  for port in "$@"; do
    if port_open "$port"; then
      echo "$port"
      return 0
    fi
  done
  return 1
}

SOCKS_PORT="$(first_open 10808 1080 7891 7890 || true)"
HTTP_PORT="$(first_open 10809 10808 7890 8118 20171 || true)"

if [[ -z "$SOCKS_PORT" ]]; then
  SOCKS_PORT=10808
  echo "warning: no SOCKS listen port found; defaulting to ${SOCKS_PORT}" >&2
  echo "         start v2rayN/Xray before docker compose up" >&2
fi
if [[ -z "$HTTP_PORT" ]]; then
  HTTP_PORT="$SOCKS_PORT"
  echo "warning: no HTTP proxy port found; using ${HTTP_PORT} (mixed inbound)" >&2
fi

cat > "$OUT" <<EOF
# Generated by generate-docker-override.sh — do not commit.
# Host network so 127.0.0.1 inside the container is the host's Xray/v2rayN.
services:
  bot:
    network_mode: host
    environment:
      HTTP_PROXY: http://127.0.0.1:${HTTP_PORT}
      HTTPS_PROXY: http://127.0.0.1:${HTTP_PORT}
      NO_PROXY: localhost,127.0.0.1
      ALL_PROXY: socks5://127.0.0.1:${SOCKS_PORT}
      TELEGRAM_PROXY_URL: socks5://127.0.0.1:${SOCKS_PORT}
EOF

echo "wrote $OUT"
echo "  SOCKS5  127.0.0.1:${SOCKS_PORT}  -> TELEGRAM_PROXY_URL / ALL_PROXY"
echo "  HTTP    127.0.0.1:${HTTP_PORT}   -> HTTP_PROXY / HTTPS_PROXY"
echo
echo "next:"
echo "  curl -s --max-time 5 -x \"socks5://127.0.0.1:${SOCKS_PORT}\" https://api.telegram.org"
echo "  docker compose up -d --build"
echo "  docker compose logs -f | grep telegram_proxy"
