"""Short callback_data builders. Telegram limit is 64 bytes."""

NAV_MAIN = "n:m"
NAV_CANCEL = "n:c"
NAV_BACK = "n:b"
NAV_SETTINGS = "n:s"
NAV_HISTORY = "n:h"
NAV_STATS = "n:st"
NAV_ADMIN = "n:a"
NAV_METRICS = "n:cm"
NAV_MARKERS = "n:mk"
NAV_BALANCE = "n:bal"
NAV_GUIDE = "n:g"

ADMIN_UPDATES = "ad:upd"
ADMIN_DEPLOY_OK = "ad:upd:ok"
ADMIN_DEPLOY_NO = "ad:upd:no"

ENTRY_CIG = "e:cig"
ENTRY_FOOL = "e:fool"
ENTRY_SNUS = "e:sns"
ENTRY_SLEEP = "e:slp"
ENTRY_CAF = "e:caf"
ENTRY_ALC = "e:alc"
ENTRY_ACT = "e:act"
