"""Short callback_data builders. Telegram limit is 64 bytes."""

NAV_MAIN = "n:m"
NAV_CANCEL = "n:c"
NAV_BACK = "n:b"
NAV_SETTINGS = "n:s"
NAV_HISTORY = "n:h"
NAV_STATS = "n:st"
NAV_ADMIN = "n:a"
NAV_METRICS = "n:cm"
NAV_DAY = "n:d"
NAV_BALANCE = "n:bal"

ENTRY_CIG = "e:cig"
ENTRY_SNUS = "e:sns"
ENTRY_SLEEP = "e:slp"
ENTRY_MOOD = "e:md"
ENTRY_WB = "e:wb"
ENTRY_CAF = "e:caf"
ENTRY_ALC = "e:alc"
ENTRY_ACT = "e:act"
ENTRY_NOTE = "e:nt"
